name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-creahia:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/energyandcleanair/creahia/ci-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies (no upgrade)
        run: |
          Rscript -e 'pak::local_install_deps(".", ask = FALSE, upgrade = FALSE)'

      - name: Run tests
        run: |
          Rscript -e 'devtools::test(stop_on_failure = TRUE)'
