name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-creahia:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/energyandcleanair/creahia/ci-image:feat-fixing_tests
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        GIS_DIR: /work/gis
        CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check GIS data availability
        run: |
          # Check if GIS data was baked into the CI image
          if [ -d "$GIS_DIR/population" ] && [ -d "$GIS_DIR/boundaries" ]; then
            echo "GIS data found in CI image:"
            ls -la $GIS_DIR/population/
            ls -la $GIS_DIR/boundaries/
          else
            echo "GIS data not found in CI image - tests may run with reduced functionality"
          fi

      - name: Install dependencies (no upgrade)
        run: |
          Rscript -e 'pak::local_install_deps(".", ask = FALSE, upgrade = FALSE)'

      - name: Run tests
        run: |
          Rscript -e 'devtools::test(stop_on_failure = TRUE)'
